print("       *       ")
print("      ***      ")
print("     *****     ")
print("    *******    ")
print("   *********   ")
print("  ***********  ")
print(" ************* ")
print("***************")
print("       H       ")
print("       H       ")
print("       H       ")